config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :destroy]
  resources :events, only: [:new, :create, :show, :index]
  resources :event_attendees, only: [:index, :new, :create, :update]
  get '/accept_invitation', to: 'event_attendees#accept_invitation', as: 'accept_invitation'
  root "users#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :event_attendee
  belongs_to :creator, class_name: "User"

  scope :past, -> { where("event_date < :time_now",
    {time_now: Time.now}) }

  scope :upcoming, -> { where("event_date >= :time_now",
    {time_now: Time.now}) }

  # def self.past
  #   @past = Event.where("event_date < :time_now",
  #     {time_now: Time.now})
  # end

  # def self.upcoming
  #   @upcoming = Event.where("event_date > :time_now",
  #     {time_now: Time.now})
  # end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

  attr_accessor :invited_user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_attendees, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendees
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"

  def attending? event_id
    self.event_attendees.find(event_id).attending
  end

  def not_attending? event_id
    !self.event_attendees.find(event_id).attending
  end

  def upcoming_events
    self.attended_events.where("event_date > :time_now",
      {time_now: Time.now})
  end

  def previous_events
    self.attended_events.where("event_date < :time_now",
      {time_now: Time.now})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  
  def current_user
    return unless session[:current_user_id]
    @current_user = User.find(session[:current_user_id])
  end

  def require_login
    return if session[:current_user_id]

    redirect_to new_user_path
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  helper_method :current_user

  def new
    cookies[:event_id] = params[:event_id]
    @invite = EventAttendee.new
  end

  def create
    @event = Event.find(cookies[:event_id])
    @user = User.where(username: params[:event_attendee][:invited_user]).first
    @invite = EventAttendee.new

    render :new and return if @user.nil?

    @invite.attended_event_id = @event.id
    @invite.event_attendee_id = @user.id
    
    if @invite.save
      redirect_to event_path(@event)
    else
      render :new
    end  
  end

  def index
    invites = EventAttendee.where(event_attendee_id: current_user.id, attending: false)
    @events = invites.map { |invite| Event.find(invite.attended_event_id) }
  end

  def accept_invitation
    event_invited_to = EventAttendee.where(event_attendee_id: current_user.id, attended_event_id: params[:event_id])[0]
    event_invited_to.attending = true
    event_invited_to.save
    
    redirect_to event_attendees_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :current_user
  
  def new
    @event = Event.new
  end

  def create
    @user = User.find session[:current_user_id]
    @event = @user.created_events.build(event_params)
    @event.creator_id = session[:current_user_id]

    @user.attended_events << @event

    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
    @previous_events = Event.past
    @upcoming_events = Event.upcoming
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :description, :event_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  helper_method :current_user

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    
    session[:current_user_id] = @user.id

    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.previous_events
  end

  def destroy
    session[:current_user_id] = nil

    redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendees/_header.html.erb
<div class='container is-fluid'>
  <div class='header'>
    <div class='container' id='navbar-wrapper'>
      <div class='level'>
        <div class='level-left'>
          <div class='level-item'>
            <div class='button'>
              <%= link_to 'Sign Out', user_path(current_user), method: :delete %>
            </div>
            <div class='button'>
              <%= link_to "Create an Event", new_event_path %>
            </div>
            <div class='button'>
              <%= link_to 'My Events', user_path(current_user) %>
            </div>
            <div class='button'>
              <%= link_to "Find Events", events_path %>
            </div>
          </div> 
        </div>  
        <div class='level-right'>
          <div class='level-item'>
            <div class="field has-addons">
              <p class="control">
                <input class="input" type="text" placeholder="Find an Event..">
              </p>
              <p class="control">
                <button class="button">
                  Search
                </button>
              </p>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>  
</div>

app/views/event_attendees/index.html.erb
<%= render 'header' %>
<div class='section'>   
  <div class='container'>
    <div class='title is-3'>
      <h3><%= current_user.username %>'s Invites</h3>
    </div>
    <div class='events-container'>
      <div class='container' id='events-attended-container'>
        <% if current_user.event_attendees.none? %>
          <div class='columns is-vcentered'>
            <div class='column'>
              <div class='events-none'>
                <p>No Invites :(</p>
              </div>
            </div>  
          </div>    
        <% else %>
          <div class='columns is-multiline is-variable is-3' id='events-container'>
            <% @events.each do |event| %>
              <div class='column is-one-quarter' id='event'>
                <div class='event-wrapper'>
                  <div class='title is-5'>
                    <%= event.event_name %>
                  </div>
                  <div class='subtitle is-6'>
                    <%= event.description %>
                  </div>
                  <div class='navigation'>
                    <div class='button'>
                      <%= link_to 'See this Event', event_path(event) %>
                    </div>
                    <div class='button'>
                      <%= link_to 'Accept invitation', accept_invitation_path(event_id: event.id) %>
                    </div>
                  </div>
                </div>  
              </div>  
            <% end %> 
          </div>
        <% end %>
      </div>
    </div>  
  </div>
</div>    

app/views/event_attendees/new.html.erb
<%= form_for(@invite) do |f| %>
  <%= f.text_field :invited_user %>
  <%= f.submit %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= f.text_field :event_name, placeholder: 'Event Name' %>
  <%= f.text_field :description, as: :text, placeholder: 'Description' %>
  <div>
    <%= f.datetime_select :event_date, {ampm: true, 
                                        minute_step: 15,
                                        order: [:day, :month, :year]},
                                        {class: 'form-control'} %>
  </div>                                      
  <%= f.submit "Create Event!" %>
<% end %>  

app/views/events/_header.html.erb
<div class='header'>
  <%= link_to 'Sign Out', user_path(current_user), method: :delete %>
</div>
<div class='section'>  
  <div class='container' style='margin: 0px;'>
    <div class='header'>
      <div class='level'>
        <div class='level-left'>
          <div class='level-item'>
            <div class='button'>
              <%= link_to 'All Events', events_path %>
            </div>
            <div class='button'>
              <%= link_to 'My Events', user_path(current_user) %>
            </div>
          </div>  
        </div>  
        <div class='level-right'>
          <div class='level-item'>
            <div class="field has-addons">
              <p class="control">
                <input class="input" type="text" placeholder="Find an Event..">
              </p>
              <p class="control">
                <button class="button">
                  Search
                </button>
              </p>
            </div>
          </div>
        </div>  
      </div>
    </div>  
  </div>
</div>  

app/views/events/_user_actions.html.erb
<div class='header'>
  <%= link_to 'Sign Out', user_path(current_user), method: :delete %>
</div>

app/views/events/index.html.erb
<%= render 'header' %>
<div class='section'> 
  <div class='container'>
    <div class='title is-3'>
      <h3>All Events</h3>
    </div>
    <div class='events-container'>
      <div class='container'>
        <div class='title is-4'>
          <h4>Upcoming events</h4>
        </div>
        <% if @upcoming_events.none? %>
          <div class='columns is-vcentered'>
            <div class='column'>
              <div class='events-none'>
                <p>No upcoming events</p>
              </div>
            </div>  
          </div>   
        <% else %>  
          <div class='columns is-multiline is-variable is-3' id='events-container'>
            <% @upcoming_events.each do |event| %>
              <div class='column is-one-quarter'>
                <div class='event-wrapper'>
                  <div class='title is-5'>
                    <%= event.event_name %>
                  </div>
                  <div class='subtitle is-6'>
                    <%= event.description %>
                  </div>
                  <div class='navigation'>
                    <div class='button'>
                      <%= link_to 'See this Event', event_path(event) %>
                    </div>
                  </div>
                </div>
              </div>  
            <% end %>
          </div>  
        <% end %>  
        <div class='title is-4'>
          <h4>Previous events</h4>
        </div>
        <% if @previous_events.none? %>
          <div class='columns is-vcentered'>
            <div class='column'>
              <div class='events-none'>
                <p>No upcoming events</p>
              </div>
            </div>  
          </div>   
        <% else %>  
          <div class='columns is-multiline is-variable is-3' id='events-container'>
            <% @previous_events.each do |event| %>
              <div class='column is-one-quarter' id='event'>
                <div class='event-wrapper'>
                  <div class='title is-5'>
                    <%= event.event_name %>
                  </div>
                  <div class='subtitle is-6'>
                    <%= event.description %>
                  </div>
                  <div class='navigation'>
                    <div class='button'>
                      <%= link_to 'See this Event', event_path(event) %>
                    </div>
                  </div>
                </div>
              </div>  
            <% end %>
          </div>  
        <% end %> 
      </div>     
    </div>    
  </div>  
</div>

app/views/events/new.html.erb
<div class='section'>
  <div class='container'>
    <div class='title'>
      Create an Event
      <div class='subtitle is-5'>
        You know you want to..
      </div>
    </div>
  </div>  
</div>
<div class='section'>
  <div class='container'>
    <%= render 'form' %>
  </div>
</div>  

app/views/events/show.html.erb
<%= render 'header' %>
<div class='section'>
  <div class='container'>  
    <div class='title'>
      <%= @event.event_name %>
    </div>
    <div class='subtitle'>
      <%= @event.description %>
    </div>
    <div class='event-creator' style="font-size:16px">
      Created by <%= link_to @event.creator.username, user_path(@event.creator) %>
    </div>
  </div>  
</div>
<div class='section' style='padding-top:0px'>
  <div class='container'>  
    <% if @event.attendees.any? %>
      Attending this Event:
      <div class='attendees'>
        <% @event.attendees.each do |attendee| %>
          <li class='attendee'>
            <%= attendee.username %>
          </li>
        <% end %>  
      </div>
    <% else %>
      <div class='attendees'>
        Be the first to attend this event!
      </div>
    <% end %>
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :username %>
  <%= f.submit %>
<% end %>

app/views/users/_header.html.erb
<div class='container is-fluid'>
  <div class='header'>
    <div class='container' id='navbar-wrapper'>
      <div class='level'>
        <div class='level-left'>
          <div class='level-item'>
            <div class='button'>
              <%= link_to 'Sign Out', user_path(current_user), method: :delete %>
            </div>
            <div class='button'>
              <%= link_to "Create an Event", new_event_path %>
            </div>
            <div class='button'>
              <%= link_to "Find Events", events_path %>
            </div>
            <div class='button'>
              <%= link_to 'My Invites', event_attendees_path %>
            </div>
          </div> 
        </div>  
        <div class='level-right'>
          <div class='level-item'>
            <div class="field has-addons">
              <p class="control">
                <input class="input" type="text" placeholder="Find an Event..">
              </p>
              <p class="control">
                <button class="button">
                  Search
                </button>
              </p>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>  
</div>

app/views/users/new.html.erb
<section class="section">
  <div class='columns is-centered'>
    <div>
      <div class="container">
        <h1 class="title">
          Welcome to EventWorld
        </h1>
        <p class="subtitle">
          Your first stop for Events!
        </p>
      </div>
    </div>  
  </div>  
</section>
<div class='columns is-centered'>
  <div class="column is-narrow">
    <%= form_for @user do |f| %>
      <%= f.text_field :username %>
      <%= f.submit "Sign In" %>
    <% end %>  
  </div>
</div>  

app/views/users/show.html.erb
<%= render 'header' %>
<div class='section'>   
  <div class='container'>
    <div class='title is-3'>
      <h2><%= @user.username %>'s Attended events</h2>
    </div>
    <div class='events-container'>
      <div class='container' id='events-attended-container'>
        <div class='title is-4'>
          <h4>Upcoming events</h4>
        </div>
        <% if @user.upcoming_events.none? %>
          <div class='columns is-vcentered'>
            <div class='column'>
              <div class='events-none'>
                <p>No upcoming events</p>
              </div>
            </div>  
          </div>    
        <% else %>
          <div class='columns is-multiline is-variable is-3' id='events-container'>
            <% @user.upcoming_events.each do |event| %>
              <div class='column is-one-quarter' id='event'>
                <div class='event-wrapper'>
                  <div class='title is-5'>
                    <%= event.event_name %>
                  </div>
                  <div class='subtitle is-6'>
                    <%= event.description %>
                  </div>
                  <div class='navigation'>
                    <div class='button'>
                      <%= link_to 'See this Event', event_path(event) %>
                    </div>
                  </div>
                </div>  
              </div>  
            <% end %> 
          </div>
        <% end %>  
        <div class='title is-4'>
          <h4>Previous events</h4>
        </div>
        <% if @user.previous_events.none? %>
          <div class='columns is-vcentered'>
            <div class='column'>
              <div class='events-none'>
                <p>No previous events</p>
              </div>
            </div>  
          </div>  
        <% else %>
          <div class='columns is-multiline is-variable is-3' id='events-container'>
            <% @user.previous_events.each do |event| %>
              <div class='column is-one-quarter' id='event'>
                <div class='event-wrapper'>
                  <div class='title is-5'>
                    <%= event.event_name %>
                  </div>
                  <div class='subtitle is-6'>
                    <%= event.description %>
                  </div>
                  <div class='navigation'>
                    <div class='button'>
                      <%= link_to 'See this Event', event_path(event) %>
                    </div>
                  </div>
                </div>  
              </div>  
            <% end %> 
          </div>
        <% end %>  
      </div>
    </div>
  </div>
    <div class='container' style='padding-top: 24px'>
    <div class="events-created">
      <div class='title is-3'>
        <h2><%= @user.username %>'s Created events</h2>
      </div>
      <div class='container' id='events-created-container'>
        <div class='columns is-multiline is-variable is-3' id='events-container'>
          <% @user.created_events.each do |event| %>
            <div class='column is-one-quarter' id='event'>
              <div class='event-wrapper'>
                <div class='title is-5'>
                  <%= event.event_name %>
                </div>
                <div class='subtitle is-6'>
                  <%= event.description %>
                </div>
                <div class='navigation'>
                  <div class='button'>
                    <%= link_to 'See this Event', event_path(event) %>
                  </div>
                  <div class='button'>
                    <%= link_to 'Send an Invitation', new_event_attendee_path(event_id: event.id) %>
                  </div>
                </div>
              </div>  
            </div>  
          <% end %>  
        </div>
      </div>  
    </div>
  </div>
</div>